trigger:
- main

pool:
  name: SelfHostedPool

steps:

- script: |
    sudo apt update
    sudo apt install -y unzip wget
    wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    unzip -o terraform_1.5.7_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
  displayName: Install Terraform

- script: terraform version
  displayName: Check Terraform Version

# 👉 DEBUG: show files
- script: ls -la
  displayName: Check Files

# Terraform Init
- script: terraform init -no-color
  displayName: Terraform Init
  workingDirectory: $(System.DefaultWorkingDirectory)
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

# Terraform Plan
- script: terraform plan -no-color
  displayName: Terraform Plan
  workingDirectory: $(System.DefaultWorkingDirectory)
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

# Terraform Apply
- script: terraform apply -auto-approve
  displayName: Terraform Apply
  workingDirectory: $(System.DefaultWorkingDirectory)
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)